import type {
  Pet,
  Product,
  Shop,
  ServiceProvider,
  ServicePackage,
  Order,
  Subscription,
  SubscriptionBox,
  CommunityPost,
  AdoptionListing,
  Article,
  BoardingFacility,
  MembershipPlan,
  Review,
  DashboardStats,
  InventoryItem,
  DashboardOrder,
  User,
  Booking,
  EmergencyVet,
  ToxicSubstance,
  CartItem,
} from "@/types"

// ─── Current User ────────────────────────────────────────────────────────────

export const currentUser: User = {
  id: "user-1",
  name: "Priya Sharma",
  email: "priya.sharma@gmail.com",
  phone: "+91 98765 43210",
  avatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
  membership: "gold",
  loyaltyPoints: 4250,
  pets: [],
  addresses: [
    {
      id: "addr-1",
      label: "Home",
      line1: "42, Koramangala 4th Block",
      line2: "Near Sony Signal",
      city: "Bangalore",
      state: "Karnataka",
      pincode: "560034",
      isDefault: true,
    },
    {
      id: "addr-2",
      label: "Office",
      line1: "WeWork Galaxy, Residency Road",
      city: "Bangalore",
      state: "Karnataka",
      pincode: "560025",
      isDefault: false,
    },
  ],
}

// ─── Pets ────────────────────────────────────────────────────────────────────

export const pets: Pet[] = [
  {
    id: "pet-1",
    name: "Bruno",
    species: "dog",
    breed: "Golden Retriever",
    age: 3,
    ageGroup: "adult",
    weight: 32,
    size: "large",
    gender: "male",
    dateOfBirth: "2023-04-15",
    imageUrl: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=400&h=400&fit=crop",
    healthConditions: ["Mild hip dysplasia"],
    allergies: ["Chicken"],
    isSpayedNeutered: true,
    microchipId: "985141002345678",
    vaccinations: [
      {
        id: "vax-1",
        name: "Rabies",
        date: "2025-11-10",
        nextDueDate: "2026-11-10",
        veterinarian: "Dr. Meera Nair",
        status: "completed",
      },
      {
        id: "vax-2",
        name: "DHPP",
        date: "2025-09-15",
        nextDueDate: "2026-09-15",
        veterinarian: "Dr. Meera Nair",
        status: "completed",
      },
      {
        id: "vax-3",
        name: "Bordetella",
        date: "2025-06-20",
        nextDueDate: "2026-04-20",
        veterinarian: "Dr. Meera Nair",
        status: "upcoming",
      },
      {
        id: "vax-4",
        name: "Leptospirosis",
        date: "2025-09-15",
        nextDueDate: "2026-09-15",
        veterinarian: "Dr. Meera Nair",
        status: "completed",
      },
    ],
    medicalHistory: [
      {
        id: "med-1",
        date: "2025-11-10",
        type: "vaccination",
        title: "Annual Rabies Vaccination",
        description: "Administered rabies booster. No adverse reactions observed.",
        veterinarian: "Dr. Meera Nair",
      },
      {
        id: "med-2",
        date: "2025-08-22",
        type: "checkup",
        title: "Routine Health Checkup",
        description:
          "Weight stable at 32kg. Mild hip dysplasia noted, recommended joint supplements. Teeth cleaning scheduled.",
        veterinarian: "Dr. Meera Nair",
      },
      {
        id: "med-3",
        date: "2025-05-03",
        type: "prescription",
        title: "Joint Supplement Prescription",
        description:
          "Started on glucosamine-chondroitin supplement for hip support. Recheck in 3 months.",
        veterinarian: "Dr. Meera Nair",
      },
    ],
  },
  {
    id: "pet-2",
    name: "Whiskers",
    species: "cat",
    breed: "Persian",
    age: 5,
    ageGroup: "adult",
    weight: 4.5,
    size: "medium",
    gender: "female",
    dateOfBirth: "2021-08-20",
    imageUrl: "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop",
    healthConditions: [],
    allergies: ["Dairy"],
    isSpayedNeutered: true,
    vaccinations: [
      {
        id: "vax-5",
        name: "FVRCP",
        date: "2025-10-05",
        nextDueDate: "2026-10-05",
        veterinarian: "Dr. Arjun Mehta",
        status: "completed",
      },
      {
        id: "vax-6",
        name: "Rabies",
        date: "2025-10-05",
        nextDueDate: "2026-10-05",
        veterinarian: "Dr. Arjun Mehta",
        status: "completed",
      },
    ],
    medicalHistory: [
      {
        id: "med-4",
        date: "2025-10-05",
        type: "checkup",
        title: "Annual Wellness Exam",
        description:
          "Healthy weight, beautiful coat. Dental tartar forming on upper molars, recommend dental cleaning soon.",
        veterinarian: "Dr. Arjun Mehta",
      },
    ],
  },
  {
    id: "pet-3",
    name: "Coco",
    species: "dog",
    breed: "Shih Tzu",
    age: 1,
    ageGroup: "puppy",
    weight: 5,
    size: "small",
    gender: "female",
    dateOfBirth: "2025-02-10",
    imageUrl: "https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=400&h=400&fit=crop",
    healthConditions: [],
    allergies: [],
    isSpayedNeutered: false,
    vaccinations: [
      {
        id: "vax-7",
        name: "DHPP (1st dose)",
        date: "2025-04-10",
        nextDueDate: "2025-05-10",
        veterinarian: "Dr. Meera Nair",
        status: "completed",
      },
      {
        id: "vax-8",
        name: "Rabies",
        date: "2025-06-10",
        nextDueDate: "2026-06-10",
        veterinarian: "Dr. Meera Nair",
        status: "completed",
      },
      {
        id: "vax-9",
        name: "Kennel Cough",
        date: "",
        nextDueDate: "2026-04-15",
        veterinarian: "",
        status: "upcoming",
      },
    ],
    medicalHistory: [],
  },
]

// ─── Products ────────────────────────────────────────────────────────────────

export const products: Product[] = [
  {
    id: "prod-1",
    name: "Royal Canin Golden Retriever Adult Dry Food",
    brand: "Royal Canin",
    category: "food",
    petType: ["dog"],
    description:
      "Specially formulated for Golden Retrievers over 15 months. Supports skin & coat health with EPA & DHA. Cardiac health support with taurine and L-carnitine.",
    price: 4599,
    originalPrice: 5199,
    subscriptionPrice: 4139,
    rating: 4.7,
    reviewCount: 1243,
    imageUrl: "https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=600&h=400&fit=crop",
      "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&h=400&fit=crop",
      "https://images.unsplash.com/photo-1583337130417-13571fc53125?w=600&h=400&fit=crop",
    ],
    inStock: true,
    stockCount: 156,
    weight: "12kg",
    ingredients: [
      "Chicken",
      "Rice",
      "Fish Oil",
      "Beet Pulp",
      "Taurine",
      "L-Carnitine",
    ],
    nutritionalInfo: {
      Protein: "26%",
      Fat: "14%",
      Fiber: "2.7%",
      "Calories (kcal/kg)": "3756",
    },
    breedSpecific: ["Golden Retriever"],
    ageGroup: ["adult"],
    tags: ["bestseller", "breed-specific", "subscription-eligible"],
  },
  {
    id: "prod-2",
    name: "Whiskas Ocean Fish Adult Cat Food",
    brand: "Whiskas",
    category: "food",
    petType: ["cat"],
    description:
      "Complete nutrition for adult cats with real ocean fish. Rich in omega fatty acids for healthy skin and shiny coat.",
    price: 799,
    originalPrice: 899,
    subscriptionPrice: 719,
    rating: 4.3,
    reviewCount: 876,
    imageUrl: "https://images.unsplash.com/photo-1535930749574-1399327ce78f?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1535930749574-1399327ce78f?w=600&h=400&fit=crop",
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=400&fit=crop",
    ],
    inStock: true,
    stockCount: 340,
    weight: "1.2kg",
    ageGroup: ["adult"],
    tags: ["value-pick", "subscription-eligible"],
  },
  {
    id: "prod-3",
    name: "KONG Classic Dog Toy - Large",
    brand: "KONG",
    category: "toys",
    petType: ["dog"],
    description:
      "World-famous KONG Classic in large size for strong chewers. Fill with treats for hours of enrichment. Ultra-durable natural rubber.",
    price: 899,
    rating: 4.8,
    reviewCount: 2341,
    imageUrl: "https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?w=600&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?w=600&h=400&fit=crop"],
    inStock: true,
    stockCount: 89,
    tags: ["bestseller", "durable"],
  },
  {
    id: "prod-4",
    name: "Drools Chicken and Egg Puppy Food",
    brand: "Drools",
    category: "food",
    petType: ["dog"],
    description:
      "Real chicken #1 ingredient. Complete nutrition for growing puppies. DHA for brain development, calcium for strong bones.",
    price: 1299,
    subscriptionPrice: 1169,
    rating: 4.4,
    reviewCount: 2156,
    imageUrl: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&h=400&fit=crop"],
    inStock: true,
    stockCount: 224,
    weight: "3kg",
    ageGroup: ["puppy"],
    tags: ["budget-friendly", "subscription-eligible"],
  },
  {
    id: "prod-5",
    name: "Himalaya Erina-EP Anti-Tick Shampoo",
    brand: "Himalaya",
    category: "grooming_supplies",
    petType: ["dog", "cat"],
    description:
      "Herbal anti-tick and flea shampoo with natural ingredients. Gentle on skin while eliminating ectoparasites. Pleasant herbal fragrance.",
    price: 340,
    originalPrice: 399,
    rating: 4.2,
    reviewCount: 567,
    imageUrl: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=600&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=600&h=400&fit=crop"],
    inStock: true,
    stockCount: 180,
    weight: "200ml",
    tags: ["herbal", "anti-tick"],
  },
  {
    id: "prod-6",
    name: "Hill's Prescription Diet k/d Kidney Care",
    brand: "Hill's",
    category: "food",
    petType: ["dog"],
    description:
      "Veterinary prescription diet for kidney care. Reduced phosphorus and sodium, controlled protein to support kidney function.",
    price: 5899,
    rating: 4.6,
    reviewCount: 312,
    imageUrl: "https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=600&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=600&h=400&fit=crop"],
    inStock: true,
    stockCount: 45,
    weight: "8.5kg",
    isPrescriptionRequired: true,
    ageGroup: ["adult", "senior"],
    tags: ["prescription", "kidney-care"],
  },
  {
    id: "prod-7",
    name: "FreshPaws Raw Chicken Patties",
    brand: "FreshPaws",
    category: "food",
    petType: ["dog"],
    description:
      "Human-grade raw chicken patties. Flash frozen for freshness. BARF diet compliant. No preservatives, no fillers.",
    price: 1899,
    rating: 4.5,
    reviewCount: 189,
    imageUrl: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=400&fit=crop"],
    inStock: true,
    stockCount: 34,
    weight: "1kg (20 patties)",
    isFreshFood: true,
    expiryDate: "2026-04-15",
    tags: ["raw-food", "fresh", "cold-chain"],
  },
  {
    id: "prod-8",
    name: "Pedigree Dentastix Large Dogs",
    brand: "Pedigree",
    category: "treats",
    petType: ["dog"],
    description:
      "Daily oral care treats that reduce plaque and tartar buildup. X-shape design cleans between teeth. For dogs 25kg+.",
    price: 499,
    subscriptionPrice: 449,
    rating: 4.3,
    reviewCount: 1567,
    imageUrl: "https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=600&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=600&h=400&fit=crop"],
    inStock: true,
    stockCount: 290,
    weight: "28 sticks",
    tags: ["dental-care", "daily-use", "subscription-eligible"],
  },
  {
    id: "prod-9",
    name: "Tractive GPS Dog Tracker",
    brand: "Tractive",
    category: "accessories",
    petType: ["dog", "cat"],
    description:
      "Real-time GPS tracking for pets. Live location, virtual fences, activity monitoring. Waterproof. Subscription required for GPS service.",
    price: 3499,
    originalPrice: 4499,
    rating: 4.1,
    reviewCount: 423,
    imageUrl: "https://images.unsplash.com/photo-1560807707-8cc77767d783?w=600&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1560807707-8cc77767d783?w=600&h=400&fit=crop"],
    inStock: true,
    stockCount: 28,
    isNew: true,
    tags: ["tech", "gps", "safety"],
  },
  {
    id: "prod-10",
    name: "Fluval 207 Performance Canister Filter",
    brand: "Fluval",
    category: "aquarium",
    petType: ["fish"],
    description:
      "Multi-stage filtration for aquariums up to 220L. Ultra-quiet operation. Includes all filter media. Quick-change mechanical baskets.",
    price: 12999,
    rating: 4.6,
    reviewCount: 87,
    imageUrl: "https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=600&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=600&h=400&fit=crop"],
    inStock: true,
    stockCount: 12,
    tags: ["aquarium", "filter", "premium"],
  },
  {
    id: "prod-11",
    name: "SmartyPaws Hip & Joint Supplement",
    brand: "SmartyPaws",
    category: "health",
    petType: ["dog"],
    description:
      "Glucosamine, chondroitin, MSM and omega-3s. Soft chew supplement for joint mobility and comfort. Vet recommended.",
    price: 1599,
    subscriptionPrice: 1439,
    rating: 4.5,
    reviewCount: 645,
    imageUrl: "https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=600&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=600&h=400&fit=crop"],
    inStock: true,
    stockCount: 78,
    weight: "60 chews",
    tags: ["joint-health", "supplement", "subscription-eligible"],
  },
  {
    id: "prod-12",
    name: "CatHoliday Scratching Post Tower",
    brand: "CatHoliday",
    category: "accessories",
    petType: ["cat"],
    description:
      "Multi-level cat tree with sisal scratching posts, hammock, condo and dangling toys. Sturdy base prevents tipping.",
    price: 4299,
    originalPrice: 5499,
    rating: 4.4,
    reviewCount: 334,
    imageUrl: "https://images.unsplash.com/photo-1587764379873-97837921fd44?w=600&h=400&fit=crop",
    images: ["https://images.unsplash.com/photo-1587764379873-97837921fd44?w=600&h=400&fit=crop"],
    inStock: true,
    stockCount: 16,
    tags: ["cat-furniture", "scratching", "multi-level"],
  },
]

// ─── Shops ───────────────────────────────────────────────────────────────────

export const shops: Shop[] = [
  {
    id: "shop-1",
    name: "Paws & Claws Pet Shop",
    description:
      "Hyderabad's most trusted pet shop since 2015. Full-service pet care including grooming, vet consultations, and 500+ products across all pet types.",
    imageUrl: "https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?w=100&h=100&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=800&h=450&fit=crop",
    address: "Road No. 12, Banjara Hills, Hyderabad",
    city: "Hyderabad",
    distance: 2.3,
    rating: 4.6,
    reviewCount: 892,
    isOpen: true,
    openingHours: "9:00 AM - 9:00 PM",
    phone: "+91 40 2334 5678",
    services: ["grooming", "vet"],
    brands: ["Royal Canin", "Pedigree", "Whiskas", "Drools", "Himalaya"],
    petTypes: ["dog", "cat", "bird", "fish"],
    isFavorite: true,
    deliveryEta: "30-45 min",
  },
  {
    id: "shop-2",
    name: "The Pet Stop",
    description:
      "Premium pet boutique specializing in exotic pets, organic food, and international brands. Expert staff for personalized recommendations.",
    imageUrl: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=100&h=100&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1601758003122-53c40e686a19?w=800&h=450&fit=crop",
    address: "100 Feet Road, Indiranagar, Bangalore",
    city: "Bangalore",
    distance: 1.5,
    rating: 4.8,
    reviewCount: 1567,
    isOpen: true,
    openingHours: "10:00 AM - 8:00 PM",
    phone: "+91 80 4112 3456",
    services: ["grooming", "vet", "training"],
    brands: ["Royal Canin", "Orijen", "Acana", "KONG", "FreshPaws"],
    petTypes: ["dog", "cat", "bird", "fish", "hamster", "reptile"],
    isFavorite: false,
    deliveryEta: "20-35 min",
  },
  {
    id: "shop-3",
    name: "Happy Tails Pet Care",
    description:
      "Family-run pet store with boarding facilities. Known for excellent grooming services and personalized pet care advice.",
    imageUrl: "https://images.unsplash.com/photo-1583511655826-05700d52f4d9?w=100&h=100&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1597633425046-08f5110420b5?w=800&h=450&fit=crop",
    address: "Sector 22, Gurgaon, Delhi NCR",
    city: "Delhi NCR",
    distance: 4.1,
    rating: 4.4,
    reviewCount: 445,
    isOpen: false,
    openingHours: "9:30 AM - 7:30 PM",
    phone: "+91 124 456 7890",
    services: ["grooming", "vet", "boarding", "training"],
    brands: ["Pedigree", "Whiskas", "Drools", "Me-O", "Purina"],
    petTypes: ["dog", "cat", "rabbit"],
    isFavorite: false,
    deliveryEta: "45-60 min",
  },
  {
    id: "shop-4",
    name: "Furry Friends Mumbai",
    description:
      "Mumbai's largest pet superstore with over 2000 products. Same-day delivery across Mumbai. Loyalty rewards program.",
    imageUrl: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=100&h=100&fit=crop",
    coverImageUrl: "https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=800&h=450&fit=crop",
    address: "Linking Road, Bandra West, Mumbai",
    city: "Mumbai",
    distance: 3.2,
    rating: 4.5,
    reviewCount: 2134,
    isOpen: true,
    openingHours: "10:00 AM - 10:00 PM",
    phone: "+91 22 2645 9012",
    services: ["grooming"],
    brands: [
      "Royal Canin",
      "Hill's",
      "Farmina",
      "Taste of the Wild",
      "Himalaya",
    ],
    petTypes: ["dog", "cat"],
    isFavorite: false,
    deliveryEta: "35-50 min",
  },
]

// ─── Service Providers ───────────────────────────────────────────────────────

export const serviceProviders: ServiceProvider[] = [
  {
    id: "sp-1",
    name: "Dr. Meera Nair",
    type: "vet",
    imageUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=200&h=200&fit=crop",
    rating: 4.9,
    reviewCount: 567,
    experience: 12,
    specializations: [
      "Small Animal Medicine",
      "Orthopedics",
      "Dermatology",
    ],
    certifications: ["BVSc", "MVSc (Small Animal Medicine)"],
    priceRange: { min: 500, max: 2000 },
    location: "Koramangala, Bangalore",
    isAvailable: true,
    bio: "Dr. Meera is a compassionate veterinarian with 12 years of experience in small animal medicine. Specializing in orthopedics and dermatology, she provides holistic care for dogs and cats.",
  },
  {
    id: "sp-2",
    name: "Suresh Kumar",
    type: "grooming",
    imageUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=200&h=200&fit=crop",
    rating: 4.7,
    reviewCount: 892,
    experience: 8,
    specializations: [
      "Breed-Specific Grooming",
      "Show Grooming",
      "De-matting",
    ],
    certifications: ["Certified Professional Pet Groomer", "NDGAA Member"],
    priceRange: { min: 800, max: 3000 },
    location: "Indiranagar, Bangalore",
    isAvailable: true,
    portfolio: [
      "https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?w=300&h=200&fit=crop",
      "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=300&h=200&fit=crop",
      "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=300&h=200&fit=crop",
      "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=300&h=200&fit=crop",
    ],
    bio: "Award-winning pet groomer with expertise in breed-specific cuts. Known for gentle handling and transformative before/after results.",
  },
  {
    id: "sp-3",
    name: "Ananya Reddy",
    type: "training",
    imageUrl: "https://images.unsplash.com/photo-1594824476967-48c8b964e05a?w=200&h=200&fit=crop",
    rating: 4.8,
    reviewCount: 345,
    experience: 6,
    specializations: [
      "Positive Reinforcement",
      "Puppy Socialization",
      "Behavioral Correction",
      "Agility",
    ],
    certifications: ["CPDT-KA Equivalent", "Fear Free Certified"],
    priceRange: { min: 800, max: 2500 },
    location: "HSR Layout, Bangalore",
    isAvailable: true,
    bio: "Certified dog trainer passionate about positive reinforcement methods. Specializes in puppy training, behavior modification, and agility.",
  },
  {
    id: "sp-4",
    name: "Dr. Arjun Mehta",
    type: "vet",
    imageUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=200&h=200&fit=crop",
    rating: 4.6,
    reviewCount: 234,
    experience: 9,
    specializations: ["Feline Medicine", "Internal Medicine", "Dental Care"],
    certifications: ["BVSc", "MVSc (Veterinary Medicine)"],
    priceRange: { min: 600, max: 1800 },
    location: "Whitefield, Bangalore",
    isAvailable: true,
    bio: "Cat specialist with 9 years of experience. Expert in feline internal medicine and dental procedures.",
  },
  {
    id: "sp-5",
    name: "Kavita Grooming Studio",
    type: "grooming",
    imageUrl: "https://images.unsplash.com/photo-1607990283143-e81e7a2c9349?w=200&h=200&fit=crop",
    rating: 4.5,
    reviewCount: 678,
    experience: 10,
    specializations: [
      "Cat Grooming",
      "Puppy First Groom",
      "Spa Treatments",
    ],
    certifications: ["International Pet Grooming Certificate"],
    priceRange: { min: 600, max: 2500 },
    location: "JP Nagar, Bangalore",
    isAvailable: false,
    portfolio: [
      "https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?w=300&h=200&fit=crop",
      "https://images.unsplash.com/photo-1601758124096-1fd661873b65?w=300&h=200&fit=crop",
    ],
    bio: "Premium grooming studio specializing in cat grooming and spa treatments. Gentle approach for anxious pets.",
  },
]

// ─── Service Packages ────────────────────────────────────────────────────────

export const servicePackages: ServicePackage[] = [
  {
    id: "pkg-1",
    name: "Full Groom - Large Dog",
    description:
      "Complete grooming including bath, blow dry, haircut, nail trim, ear cleaning, and teeth brushing",
    price: 1800,
    duration: "2-3 hours",
    serviceType: "grooming",
    petTypes: ["dog"],
    includes: [
      "Bath with breed-appropriate shampoo",
      "Blow dry & brush out",
      "Full body haircut",
      "Nail trimming",
      "Ear cleaning",
      "Teeth brushing",
      "Cologne spray",
      "Bandana",
    ],
  },
  {
    id: "pkg-2",
    name: "Bath & Blow Dry",
    description: "Refreshing bath with premium shampoo and professional blow dry",
    price: 800,
    duration: "1-1.5 hours",
    serviceType: "grooming",
    petTypes: ["dog", "cat"],
    includes: [
      "Bath with premium shampoo",
      "Conditioner treatment",
      "Professional blow dry",
      "Light brushing",
      "Cologne spray",
    ],
  },
  {
    id: "pkg-3",
    name: "Video Vet Consultation",
    description:
      "30-minute HD video consultation with a licensed veterinarian. Share pet profile and symptoms in advance.",
    price: 499,
    duration: "30 minutes",
    serviceType: "vet",
    petTypes: ["dog", "cat", "bird", "fish", "hamster", "rabbit", "reptile"],
    includes: [
      "HD Video call",
      "Pet profile review",
      "Diagnosis & advice",
      "Digital prescription",
      "24-hour follow-up chat",
    ],
  },
  {
    id: "pkg-4",
    name: "In-Clinic Vet Visit",
    description:
      "Comprehensive in-clinic examination with physical checkup, basic diagnostics, and treatment plan.",
    price: 800,
    duration: "45 minutes",
    serviceType: "vet",
    petTypes: ["dog", "cat", "bird", "hamster", "rabbit", "reptile"],
    includes: [
      "Full physical examination",
      "Weight & vitals check",
      "Diagnosis & treatment plan",
      "Digital prescription",
      "Follow-up scheduling",
    ],
  },
  {
    id: "pkg-5",
    name: "Basic Obedience Training - 8 Sessions",
    description:
      "8-session package covering sit, stay, come, heel, leash manners. Positive reinforcement methodology.",
    price: 6400,
    duration: "8 sessions (45 min each)",
    serviceType: "training",
    petTypes: ["dog"],
    includes: [
      "Initial behavioral assessment",
      "8 private training sessions",
      "Homework assignments per session",
      "Progress tracking report",
      "Phone/chat support between sessions",
    ],
  },
  {
    id: "pkg-6",
    name: "Puppy Socialization Class",
    description:
      "Group socialization class for puppies 8-16 weeks. Controlled exposure to other puppies and new experiences.",
    price: 1200,
    duration: "4 sessions (1 hour each)",
    serviceType: "training",
    petTypes: ["dog"],
    includes: [
      "Controlled puppy playgroups",
      "Exposure to new sounds & surfaces",
      "Basic command introduction",
      "Owner education & Q&A",
    ],
  },
  {
    id: "pkg-7",
    name: "Nail Trim + Ear Cleaning",
    description: "Quick grooming essentials service",
    price: 400,
    duration: "30 minutes",
    serviceType: "grooming",
    petTypes: ["dog", "cat"],
    includes: ["Nail trimming & filing", "Ear cleaning", "Paw pad check"],
  },
  {
    id: "pkg-8",
    name: "De-shedding Treatment",
    description:
      "Professional de-shedding treatment to reduce loose fur by up to 80%",
    price: 1200,
    duration: "1.5-2 hours",
    serviceType: "grooming",
    petTypes: ["dog", "cat"],
    includes: [
      "De-shedding shampoo",
      "High-velocity blow dry",
      "FURminator treatment",
      "Undercoat removal",
      "Conditioning",
    ],
  },
]

// ─── Boarding Facilities ─────────────────────────────────────────────────────

export const boardingFacilities: BoardingFacility[] = [
  {
    id: "bf-1",
    name: "PawParadise Boarding Resort",
    imageUrl: "https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?w=600&h=400&fit=crop",
      "https://images.unsplash.com/photo-1548658166-136d9f6a5c3c?w=600&h=400&fit=crop",
      "https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?w=600&h=400&fit=crop",
    ],
    rating: 4.8,
    reviewCount: 456,
    location: "Whitefield, Bangalore",
    distance: 8.2,
    amenities: [
      "AC rooms",
      "Outdoor play area",
      "Swimming pool",
      "Webcam access",
      "24/7 staff",
      "Vet on call",
    ],
    petTypes: ["dog", "cat"],
    pricing: { standard: 1200, premium: 2000, luxury: 3500 },
    capacity: 30,
    availableSpots: 8,
    hasWebcam: true,
  },
  {
    id: "bf-2",
    name: "Wagging Tails Pet Hotel",
    imageUrl: "https://images.unsplash.com/photo-1544568100-847a948585b9?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1544568100-847a948585b9?w=600&h=400&fit=crop",
      "https://images.unsplash.com/photo-1558788353-f76d92427f16?w=600&h=400&fit=crop",
    ],
    rating: 4.5,
    reviewCount: 234,
    location: "Electronic City, Bangalore",
    distance: 12.5,
    amenities: [
      "AC rooms",
      "Play area",
      "Grooming on-site",
      "Daily photo updates",
      "Night patrol",
    ],
    petTypes: ["dog"],
    pricing: { standard: 900, premium: 1500, luxury: 2500 },
    capacity: 20,
    availableSpots: 5,
    hasWebcam: false,
  },
  {
    id: "bf-3",
    name: "Furry Haven Daycare & Boarding",
    imageUrl: "https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=600&h=400&fit=crop",
      "https://images.unsplash.com/photo-1586671267731-da2cf3ceeb80?w=600&h=400&fit=crop",
      "https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=600&h=400&fit=crop",
    ],
    rating: 4.7,
    reviewCount: 567,
    location: "Koramangala, Bangalore",
    distance: 3.1,
    amenities: [
      "AC rooms",
      "Large outdoor area",
      "Webcam",
      "Agility course",
      "Personal attendant (Luxury)",
      "Vet on premises",
    ],
    petTypes: ["dog", "cat", "rabbit"],
    pricing: { standard: 1100, premium: 1800, luxury: 3000 },
    capacity: 40,
    availableSpots: 12,
    hasWebcam: true,
  },
]

// ─── Orders ──────────────────────────────────────────────────────────────────

export const orders: Order[] = [
  {
    id: "ORD-2026-8842",
    items: [
      { product: products[0], quantity: 1, isSubscription: true, subscriptionFrequency: 4 },
      { product: products[7], quantity: 2, isSubscription: false },
    ],
    status: "delivered",
    totalAmount: 5597,
    discount: 460,
    deliveryFee: 0,
    paymentMethod: "UPI",
    shippingAddress: "42, Koramangala 4th Block, Bangalore - 560034",
    createdAt: "2026-03-20",
    estimatedDelivery: "2026-03-23",
    trackingId: "SHP928374651",
    isSubscriptionOrder: true,
  },
  {
    id: "ORD-2026-8901",
    items: [
      { product: products[2], quantity: 1, isSubscription: false },
      { product: products[4], quantity: 1, isSubscription: false },
    ],
    status: "out_for_delivery",
    totalAmount: 1239,
    discount: 0,
    deliveryFee: 49,
    paymentMethod: "Credit Card",
    shippingAddress: "42, Koramangala 4th Block, Bangalore - 560034",
    createdAt: "2026-03-26",
    estimatedDelivery: "2026-03-28",
    trackingId: "SHP928374723",
    isSubscriptionOrder: false,
  },
  {
    id: "ORD-2026-8756",
    items: [
      { product: products[1], quantity: 3, isSubscription: true, subscriptionFrequency: 4 },
    ],
    status: "confirmed",
    totalAmount: 2157,
    discount: 240,
    deliveryFee: 0,
    paymentMethod: "UPI AutoPay",
    shippingAddress: "42, Koramangala 4th Block, Bangalore - 560034",
    createdAt: "2026-03-27",
    estimatedDelivery: "2026-03-30",
    isSubscriptionOrder: true,
  },
]

// ─── Bookings ────────────────────────────────────────────────────────────────

export const bookings: Booking[] = [
  {
    id: "BK-2026-1234",
    serviceType: "grooming",
    provider: serviceProviders[1],
    pet: pets[0],
    date: "2026-04-02",
    time: "10:00 AM",
    status: "confirmed",
    package: servicePackages[0],
    notes: "Please be gentle near ears, sensitive area",
    totalPrice: 1800,
  },
  {
    id: "BK-2026-1189",
    serviceType: "vet",
    provider: serviceProviders[0],
    pet: pets[2],
    date: "2026-04-05",
    time: "3:00 PM",
    status: "confirmed",
    package: servicePackages[3],
    notes: "Routine puppy checkup + vaccination",
    totalPrice: 800,
  },
  {
    id: "BK-2026-1156",
    serviceType: "grooming",
    provider: serviceProviders[1],
    pet: pets[1],
    date: "2026-03-15",
    time: "2:00 PM",
    status: "completed",
    package: servicePackages[1],
    totalPrice: 800,
  },
]

// ─── Subscriptions ───────────────────────────────────────────────────────────

export const subscriptions: Subscription[] = [
  {
    id: "sub-1",
    product: products[0],
    frequency: 4,
    quantity: 1,
    nextDelivery: "2026-04-17",
    status: "active",
    discount: 10,
    createdAt: "2025-08-10",
    pet: pets[0],
  },
  {
    id: "sub-2",
    product: products[1],
    frequency: 4,
    quantity: 3,
    nextDelivery: "2026-04-24",
    status: "active",
    discount: 10,
    createdAt: "2025-11-15",
    pet: pets[1],
  },
  {
    id: "sub-3",
    product: products[7],
    frequency: 4,
    quantity: 1,
    nextDelivery: "2026-04-17",
    status: "paused",
    discount: 10,
    createdAt: "2026-01-05",
    pet: pets[0],
  },
]

// ─── Subscription Boxes ──────────────────────────────────────────────────────

export const subscriptionBoxes: SubscriptionBox[] = [
  {
    id: "box-1",
    name: "Puppy Starter Box",
    description:
      "Everything your new puppy needs. Curated by vets for puppies 0-12 months.",
    targetPetType: "dog",
    targetAgeGroup: "puppy",
    price: 999,
    imageUrl: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=400&fit=crop",
    contents: [
      "Puppy food sample (500g)",
      "Training treats pack",
      "Chew toy",
      "Poop bags (3 months supply)",
      "Puppy care guide booklet",
    ],
    isPopular: true,
  },
  {
    id: "box-2",
    name: "Senior Dog Care Box",
    description:
      "Gentle care for aging companions. Joint support, dental care, and comfort items.",
    targetPetType: "dog",
    targetAgeGroup: "senior",
    price: 1299,
    imageUrl: "https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=600&h=400&fit=crop",
    contents: [
      "Joint supplement (30-day)",
      "Dental chew pack",
      "Orthopedic toy",
      "Senior diet sample",
      "Care tips card",
    ],
  },
  {
    id: "box-3",
    name: "Cat Surprise Box",
    description:
      "Monthly feline delight with gourmet treats, toys, and grooming essentials.",
    targetPetType: "cat",
    price: 999,
    imageUrl: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&h=400&fit=crop",
    contents: [
      "Gourmet cat food (2 varieties)",
      "Catnip toy",
      "Scratching pad",
      "Grooming wipes",
      "Treat variety pack",
    ],
    isPopular: true,
  },
  {
    id: "box-4",
    name: "Adventure Dog Box",
    description:
      "For the active pup who loves the outdoors. Trail-ready treats and gear.",
    targetPetType: "dog",
    price: 1499,
    imageUrl: "https://images.unsplash.com/photo-1583337130417-13571fc53125?w=600&h=400&fit=crop",
    contents: [
      "High-energy trail treats",
      "Collapsible water bowl",
      "Reflective leash attachment",
      "Paw balm",
      "Adventure bandana",
    ],
  },
  {
    id: "box-5",
    name: "Bird Delight Box",
    description: "Curated essentials for happy feathered friends.",
    targetPetType: "bird",
    price: 799,
    imageUrl: "https://images.unsplash.com/photo-1535930749574-1399327ce78f?w=600&h=400&fit=crop",
    contents: [
      "Seed mix variety (3 types)",
      "Mineral block",
      "Foraging toy",
      "Cage accessory",
      "Bird care guide",
    ],
  },
  {
    id: "box-6",
    name: "Birthday Celebration Box",
    description:
      "Make your pet's birthday extra special with treats, toys, and photo props!",
    targetPetType: "dog",
    price: 799,
    imageUrl: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=400&fit=crop",
    contents: [
      "Birthday bandana",
      "Pet-safe birthday cake",
      "Special treats assortment",
      "Photo props set",
      "Birthday card",
    ],
  },
]

// ─── Community Posts ─────────────────────────────────────────────────────────

export const communityPosts: CommunityPost[] = [
  {
    id: "post-1",
    author: {
      name: "Sneha Kapoor",
      avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop",
      petName: "Max",
      petBreed: "Beagle",
    },
    content:
      "Max just completed his agility training course! So proud of this little guy. From barely sitting on command to clearing all obstacles. Highly recommend Ananya as a trainer!",
    imageUrl: "https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?w=600&h=400&fit=crop",
    likes: 234,
    comments: 45,
    createdAt: "2026-03-27T14:30:00",
    isLiked: true,
    tags: ["training", "agility", "beagle"],
  },
  {
    id: "post-2",
    author: {
      name: "Vikram Patel",
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop",
      petName: "Rex",
      petBreed: "German Shepherd",
    },
    content:
      "Looking for breed-specific diet recommendations for a 3-year-old GSD. Rex has been on Royal Canin but thinking of switching to raw. Any experienced GSD parents who've made the switch?",
    likes: 89,
    comments: 67,
    createdAt: "2026-03-27T10:15:00",
    isLiked: false,
    tags: ["diet", "german-shepherd", "raw-food"],
  },
  {
    id: "post-3",
    author: {
      name: "Meghna Roy",
      avatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop",
      petName: "Mochi",
      petBreed: "Persian Cat",
    },
    content:
      "Mochi's grooming transformation at PawPalace! She went from matted fur to absolute royalty. The groomer was so patient with her anxiety. Booking again next month!",
    imageUrl: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&h=400&fit=crop",
    likes: 456,
    comments: 78,
    createdAt: "2026-03-26T18:45:00",
    isLiked: true,
    tags: ["grooming", "persian-cat", "before-after"],
  },
  {
    id: "post-4",
    author: {
      name: "Ravi Krishnan",
      avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop",
      petName: "Nemo",
      petBreed: "Clownfish Tank",
    },
    content:
      "Finally set up my 120L reef tank! Took 3 months of cycling and patience. Currently home to 2 clownfish, a royal gramma, and some soft corals. The Fluval filter from PawPalace is a game changer.",
    imageUrl: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=600&h=400&fit=crop",
    likes: 312,
    comments: 91,
    createdAt: "2026-03-25T12:00:00",
    isLiked: false,
    tags: ["aquarium", "reef-tank", "fish"],
  },
  {
    id: "post-5",
    author: {
      name: "Priya Sharma",
      avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=80&h=80&fit=crop",
      petName: "Bruno",
      petBreed: "Golden Retriever",
    },
    content:
      "Bruno turned 3 today! We celebrated with a pet-safe cake from PawPalace and he absolutely demolished it in 30 seconds flat. Happy birthday to the goodest boy!",
    imageUrl: "https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=600&h=400&fit=crop",
    likes: 567,
    comments: 123,
    createdAt: "2026-03-24T09:00:00",
    isLiked: false,
    tags: ["birthday", "golden-retriever", "celebration"],
  },
]

// ─── Adoption Listings ───────────────────────────────────────────────────────

export const adoptionListings: AdoptionListing[] = [
  {
    id: "adopt-1",
    name: "Luna",
    species: "dog",
    breed: "Indie (Mixed Breed)",
    age: "~2 years",
    gender: "female",
    description:
      "Luna is a gentle, affectionate Indie who was rescued from the streets. She's vaccinated, spayed, and house-trained. Great with kids and other dogs.",
    imageUrl: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=400&fit=crop",
    shelter: "Blue Cross of India",
    location: "Bangalore",
    isVaccinated: true,
    isSpayedNeutered: true,
    status: "available",
  },
  {
    id: "adopt-2",
    name: "Tiger",
    species: "cat",
    breed: "Tabby",
    age: "~1 year",
    gender: "male",
    description:
      "Playful tabby cat with beautiful markings. Loves chasing toys and cuddling. Indoor-only preferred. Litter trained.",
    imageUrl: "https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=600&h=400&fit=crop",
    shelter: "CUPA Animal Shelter",
    location: "Bangalore",
    isVaccinated: true,
    isSpayedNeutered: true,
    status: "available",
  },
  {
    id: "adopt-3",
    name: "Buddy & Cookie",
    species: "dog",
    breed: "Labrador Mix",
    age: "~4 months",
    gender: "male",
    description:
      "Bonded siblings looking for a forever home together. Playful, healthy, and full of energy. Started basic training.",
    imageUrl: "https://images.unsplash.com/photo-1560807707-8cc77767d783?w=600&h=400&fit=crop",
    shelter: "Charlie's Animal Rescue",
    location: "Mumbai",
    isVaccinated: true,
    isSpayedNeutered: false,
    status: "available",
  },
  {
    id: "adopt-4",
    name: "Mango",
    species: "bird",
    breed: "Budgerigar",
    age: "~6 months",
    gender: "male",
    description:
      "Bright green budgie who loves to sing. Comes with a starter cage. Surrendered by owner relocating abroad.",
    imageUrl: "https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=600&h=400&fit=crop",
    shelter: "Wings of Hope Aviary",
    location: "Chennai",
    isVaccinated: false,
    isSpayedNeutered: false,
    status: "available",
  },
]

// ─── Articles ────────────────────────────────────────────────────────────────

export const articles: Article[] = [
  {
    id: "art-1",
    title: "Complete Vaccination Guide for Puppies: What Every New Pet Parent Needs to Know",
    excerpt:
      "Understanding the puppy vaccination schedule, from core vaccines to optional boosters, and why timing matters for immunity.",
    imageUrl: "https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=600&h=400&fit=crop",
    category: "Health",
    author: "Dr. Meera Nair",
    readTime: "8 min read",
    publishedAt: "2026-03-25",
  },
  {
    id: "art-2",
    title: "Raw Diet vs Kibble: Making the Right Choice for Your Dog",
    excerpt:
      "A vet's perspective on the pros and cons of raw feeding versus commercial kibble, with breed-specific considerations.",
    imageUrl: "https://images.unsplash.com/photo-1587764379873-97837921fd44?w=600&h=400&fit=crop",
    category: "Nutrition",
    author: "Dr. Arjun Mehta",
    readTime: "12 min read",
    publishedAt: "2026-03-22",
  },
  {
    id: "art-3",
    title: "Top 10 Grooming Tips for Long-Haired Breeds",
    excerpt:
      "Professional groomer shares essential at-home grooming tips for Persian cats, Shih Tzus, and other high-maintenance coats.",
    imageUrl: "https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?w=600&h=400&fit=crop",
    category: "Grooming",
    author: "Suresh Kumar",
    readTime: "6 min read",
    publishedAt: "2026-03-20",
  },
  {
    id: "art-4",
    title: "Setting Up Your First Aquarium: A Complete Beginner's Guide",
    excerpt:
      "From tank selection to cycling to stocking, everything you need to know for a thriving freshwater aquarium.",
    imageUrl: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&h=400&fit=crop",
    category: "Fish Care",
    author: "Ravi Krishnan",
    readTime: "15 min read",
    publishedAt: "2026-03-18",
  },
]

// ─── Reviews ─────────────────────────────────────────────────────────────────

export const reviews: Review[] = [
  {
    id: "rev-1",
    author: "Sneha K.",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=60&h=60&fit=crop",
    rating: 5,
    content:
      "Royal Canin Golden Retriever food has been amazing for Bruno. His coat is shinier, digestion improved, and he loves the taste. Subscription delivery is always on time.",
    date: "2026-03-15",
    isVerified: true,
    helpful: 42,
    images: ["https://images.unsplash.com/photo-1588943211346-0908a1fb0b01?w=200&h=200&fit=crop"],
  },
  {
    id: "rev-2",
    author: "Rajesh M.",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=60&h=60&fit=crop",
    rating: 4,
    content:
      "Good quality KONG toy, keeps my Lab busy for hours. Slightly expensive but very durable. Been using it for 6 months and it's still intact.",
    date: "2026-03-10",
    isVerified: true,
    helpful: 28,
  },
  {
    id: "rev-3",
    author: "Anita S.",
    avatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=60&h=60&fit=crop",
    rating: 5,
    content:
      "Dr. Meera is the best vet we've ever had. She diagnosed our cat's condition that two other vets missed. Thorough, caring, and explains everything clearly.",
    date: "2026-03-08",
    isVerified: true,
    helpful: 67,
  },
  {
    id: "rev-4",
    author: "Karan J.",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=60&h=60&fit=crop",
    rating: 3,
    content:
      "Grooming was good but the wait time was longer than expected. The groomer was gentle with my Shih Tzu though, and the before/after photos were a nice touch.",
    date: "2026-03-05",
    isVerified: true,
    helpful: 15,
  },
]

// ─── Membership Plans ────────────────────────────────────────────────────────

export const membershipPlans: MembershipPlan[] = [
  {
    id: "mem-1",
    tier: "free",
    name: "Free",
    annualFee: 0,
    benefits: [
      "Standard shipping on orders",
      "Basic pet profile",
      "Standard vet booking rates",
      "Earn loyalty points at 1x rate",
      "Access to community features",
    ],
    pointsMultiplier: 1,
  },
  {
    id: "mem-2",
    tier: "gold",
    name: "PawPalace Gold",
    annualFee: 999,
    benefits: [
      "Free standard delivery on orders above ₹500",
      "5% discount on all grooming services",
      "Priority vet booking",
      "Earn loyalty points at 2x rate",
      "Free birthday box for your pet",
      "Early access to new products",
      "Exclusive Gold member deals",
    ],
    pointsMultiplier: 2,
    isPopular: true,
  },
  {
    id: "mem-3",
    tier: "platinum",
    name: "PawPalace Platinum",
    annualFee: 2499,
    benefits: [
      "Free delivery on ALL orders (no minimum)",
      "10% discount on grooming, vet & boarding",
      "Same-day delivery available",
      "Priority customer support",
      "Earn loyalty points at 3x rate",
      "Monthly curated subscription box",
      "Free annual health checkup for all pets",
      "Exclusive Platinum member events",
      "Personal pet care consultant",
    ],
    pointsMultiplier: 3,
  },
]

// ─── Dashboard Stats ─────────────────────────────────────────────────────────

export const dashboardStats: DashboardStats = {
  totalRevenue: 847500,
  revenueChange: 12.5,
  totalOrders: 1234,
  ordersChange: 8.3,
  activeSubscriptions: 456,
  subscriptionsChange: 15.2,
  totalCustomers: 2890,
  customersChange: 5.7,
}

// ─── Dashboard Inventory ─────────────────────────────────────────────────────

export const inventoryItems: InventoryItem[] = [
  {
    id: "inv-1",
    name: "Royal Canin Golden Retriever Adult 12kg",
    sku: "RC-GR-ADT-12",
    category: "food",
    stock: 156,
    lowStockThreshold: 20,
    price: 4599,
    status: "in_stock",
  },
  {
    id: "inv-2",
    name: "Whiskas Ocean Fish 1.2kg",
    sku: "WH-OF-ADT-12",
    category: "food",
    stock: 8,
    lowStockThreshold: 30,
    price: 799,
    status: "low_stock",
  },
  {
    id: "inv-3",
    name: "FreshPaws Raw Chicken Patties 1kg",
    sku: "FP-RCP-1K",
    category: "food",
    stock: 34,
    lowStockThreshold: 15,
    price: 1899,
    expiryDate: "2026-04-15",
    status: "expiring_soon",
  },
  {
    id: "inv-4",
    name: "KONG Classic Large",
    sku: "KNG-CLS-L",
    category: "toys",
    stock: 89,
    lowStockThreshold: 10,
    price: 899,
    status: "in_stock",
  },
  {
    id: "inv-5",
    name: "Himalaya Erina-EP Shampoo 200ml",
    sku: "HIM-ERINEP-200",
    category: "grooming_supplies",
    stock: 0,
    lowStockThreshold: 25,
    price: 340,
    status: "out_of_stock",
  },
  {
    id: "inv-6",
    name: "Hill's k/d Kidney Care 8.5kg",
    sku: "HLS-KD-85",
    category: "food",
    stock: 45,
    lowStockThreshold: 10,
    price: 5899,
    status: "in_stock",
  },
  {
    id: "inv-7",
    name: "Pedigree Dentastix Large 28pk",
    sku: "PED-DNT-L28",
    category: "treats",
    stock: 12,
    lowStockThreshold: 20,
    price: 499,
    status: "low_stock",
  },
  {
    id: "inv-8",
    name: "SmartyPaws Joint Supplement 60ct",
    sku: "SP-JNT-60",
    category: "health",
    stock: 78,
    lowStockThreshold: 15,
    price: 1599,
    status: "in_stock",
  },
]

// ─── Dashboard Orders ────────────────────────────────────────────────────────

export const dashboardOrders: DashboardOrder[] = [
  {
    id: "ORD-2026-8901",
    customer: "Priya Sharma",
    items: 2,
    total: 1239,
    status: "out_for_delivery",
    date: "2026-03-28",
    paymentMethod: "Credit Card",
  },
  {
    id: "ORD-2026-8900",
    customer: "Rajesh Menon",
    items: 3,
    total: 6798,
    status: "processing",
    date: "2026-03-28",
    paymentMethod: "UPI",
  },
  {
    id: "ORD-2026-8899",
    customer: "Sneha Kapoor",
    items: 1,
    total: 4599,
    status: "confirmed",
    date: "2026-03-28",
    paymentMethod: "UPI AutoPay",
  },
  {
    id: "ORD-2026-8898",
    customer: "Vikram Patel",
    items: 5,
    total: 12450,
    status: "packed",
    date: "2026-03-27",
    paymentMethod: "Credit Card",
  },
  {
    id: "ORD-2026-8897",
    customer: "Anita Desai",
    items: 2,
    total: 2398,
    status: "delivered",
    date: "2026-03-27",
    paymentMethod: "UPI",
  },
  {
    id: "ORD-2026-8896",
    customer: "Karan Johar",
    items: 1,
    total: 899,
    status: "delivered",
    date: "2026-03-26",
    paymentMethod: "COD",
  },
]

// ─── Cart Items ──────────────────────────────────────────────────────────────

export const cartItems: CartItem[] = [
  {
    product: products[3],
    quantity: 1,
    isSubscription: false,
  },
  {
    product: products[10],
    quantity: 1,
    isSubscription: true,
    subscriptionFrequency: 4,
  },
]

// ─── Emergency Vets ──────────────────────────────────────────────────────────

export const emergencyVets: EmergencyVet[] = [
  {
    id: "ev-1",
    name: "CESSNA Lifeline Veterinary Hospital",
    address: "4th Cross, Koramangala 5th Block, Bangalore",
    phone: "+91 80 4170 4170",
    distance: 1.8,
    is24Hours: true,
    rating: 4.7,
    imageUrl: "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=300&h=200&fit=crop",
  },
  {
    id: "ev-2",
    name: "Max Vets Specialty Hospital",
    address: "100ft Road, HAL 2nd Stage, Bangalore",
    phone: "+91 80 2529 0890",
    distance: 3.2,
    is24Hours: true,
    rating: 4.5,
    imageUrl: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=300&h=200&fit=crop",
  },
  {
    id: "ev-3",
    name: "Bangalore Pet Hospital",
    address: "Residency Road, Bangalore",
    phone: "+91 80 2221 5566",
    distance: 4.5,
    is24Hours: false,
    rating: 4.3,
    imageUrl: "https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?w=300&h=200&fit=crop",
  },
]

// ─── Toxic Substances ────────────────────────────────────────────────────────

export const toxicSubstances: ToxicSubstance[] = [
  {
    id: "tox-1",
    name: "Chocolate",
    category: "Food",
    petTypes: ["dog", "cat"],
    severity: "severe",
    symptoms: ["Vomiting", "Diarrhea", "Rapid breathing", "Seizures", "Heart failure"],
    firstAid:
      "Do not induce vomiting without vet guidance. Call emergency vet immediately. Note the type and amount consumed.",
  },
  {
    id: "tox-2",
    name: "Grapes & Raisins",
    category: "Food",
    petTypes: ["dog"],
    severity: "severe",
    symptoms: ["Vomiting", "Lethargy", "Kidney failure", "Decreased urination"],
    firstAid:
      "Call vet immediately. Even small amounts can cause kidney failure in dogs. Time is critical.",
  },
  {
    id: "tox-3",
    name: "Onions & Garlic",
    category: "Food",
    petTypes: ["dog", "cat"],
    severity: "moderate",
    symptoms: ["Lethargy", "Weakness", "Pale gums", "Red/brown urine", "Vomiting"],
    firstAid:
      "Contact vet. Symptoms may be delayed 2-5 days. Can cause anemia. Cats are especially sensitive.",
  },
  {
    id: "tox-4",
    name: "Lily Plants",
    category: "Plant",
    petTypes: ["cat"],
    severity: "fatal",
    symptoms: ["Vomiting", "Loss of appetite", "Kidney failure", "Death within 72 hours"],
    firstAid:
      "EMERGENCY - All parts of lily are toxic to cats. Rush to vet immediately. Even pollen can be fatal.",
  },
  {
    id: "tox-5",
    name: "Xylitol (Sugar-Free Sweetener)",
    category: "Food",
    petTypes: ["dog"],
    severity: "severe",
    symptoms: ["Vomiting", "Collapse", "Seizures", "Low blood sugar", "Liver failure"],
    firstAid:
      "Rush to vet immediately. Found in sugar-free gum, mints, peanut butter, and baked goods. Fast-acting toxin.",
  },
  {
    id: "tox-6",
    name: "Avocado",
    category: "Food",
    petTypes: ["dog", "cat", "bird"],
    severity: "moderate",
    symptoms: ["Vomiting", "Diarrhea", "Difficulty breathing (birds)", "Congestion"],
    firstAid:
      "Monitor for symptoms. Especially dangerous for birds. Contact vet if symptoms develop.",
  },
]
